{% set version = "19.0.1" %}

package:
  name: keyring
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
  sha256: 44e5a4e1ad1070c7cd46959a0d6c2a99588b66a6dad6fd685463b486c04855ea

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - keyring = keyring.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
  run:
    - python
    - pywin32-ctypes  # [win]
    - entrypoints
    - secretstorage  # [linux]

test:
  imports:
    - keyring
    - keyring.backends
    - keyring.tests
    - keyring.tests.backends
    - keyring.util
  commands:
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: Python Software Foundation or MIT
  license_file: LICENSE
  summary: 'Store and access your passwords safely'

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ccordoba12
