{% set version = "12.2.1" %}

package:
    name: keyring
    version: {{ version }}

source:
    fn: keyring-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/k/keyring/keyring-{{ version }}.tar.gz
    sha256: 4498eaa2e32fc69a8b36749116b670c379d36a1a9ad4ab107df1e19c8a120ffe

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - keyring=keyring.cli:main

requirements:
    host:
        - python
        - setuptools
        - setuptools_scm >=1.15.0
        - pywin32-ctypes  # [win]
        - entrypoints
    run:
        - python
        - pywin32-ctypes  # [win]
        - entrypoints

test:
    imports:
        - keyring
        - keyring.backends
        - keyring.tests
        - keyring.tests.backends
        - keyring.util
    commands:
        - keyring --help

about:
    home: https://github.com/jaraco/keyring
    license: Python Software Foundation or MIT
    license_family: MIT
    summary: 'Store and access your passwords safely.'
    description: |
      the python keyring lib provides a easy way to access the system keyring
      service from python.  it can be used in any application that needs safe
      password storage.
    doc_url: https://pypi.org/project/keyring/
    doc_source_url: https://github.com/jaraco/keyring/blob/master/readme.rst

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - ccordoba12
