{% set version = "19.2.0" %}

package:
  name: keyring
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
  sha256: 91037ccaf0c9a112a76f7740e4a416b9457a69b66c2799421581bee710a974b3

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - keyring = keyring.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
  run:
    - python
    - pywin32-ctypes  # [win]
    - entrypoints
    - secretstorage  # [linux]

test:
  imports:
    - keyring
    - keyring.backends
    - keyring.tests
    - keyring.tests.backends
    - keyring.util
  commands:
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: Python Software Foundation or MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Store and access your passwords safely'
  description: |
    the python keyring lib provides a easy way to access the system keyring
    service from python.  it can be used in any application that needs safe
    password storage.
  doc_url: https://pypi.org/project/keyring/
  doc_source_url: https://github.com/jaraco/keyring/blob/master/readme.rst

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ccordoba12
