{% set version = "23.4.0" %}

package:
  name: keyring
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
  sha256: 88f206024295e3c6fb16bb0a60fb4bb7ec1185629dc5a729f12aa7c236d01387

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - keyring = keyring.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools >=56
    - setuptools_scm >=3.4.1
    - toml
    - wheel
  run:
    - python
    - pywin32-ctypes !=0.1.0,!=0.1.1  # [win]
    - secretstorage >=3.2  # [linux]
    - importlib_metadata >=3.6
    - jeepney >=0.4.2  # [linux]

test:
  requires:
    - pip
    - pytest >=6
    - pytest-runner
    - setuptools_scm >=1.15.0
  source_files:
      - tests/*
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  commands:
    - pip check
    # skip tests on OS-X, the default keychain is not available in the
    # build environment
    - py.test -v tests  # [not osx]
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Store and access your passwords safely
  description: |
    The python keyring lib provides a easy way to access the system keyring
    service from python.  it can be used in any application that needs safe
    password storage.
  doc_url: https://pypi.org/project/keyring/
  doc_source_url: https://github.com/jaraco/keyring/blob/master/readme.rst
  dev_url: https://github.com/jaraco/keyring

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - ccordoba12
