{% set version = "23.13.1" %}

package:
  name: keyring
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
  sha256: ba2e15a9b35e21908d0aaf4e0a47acc52d6ae33444df0da2b49d41a46ef6d678

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - keyring = keyring.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - toml
    - wheel
  run:
    - python
    - pywin32-ctypes >=0.2.2  # [win]
    - secretstorage >=3.2  # [linux]
    - jeepney >=0.4.2  # [linux]
    - importlib_metadata >=4.11.4  # [py<312]
    - jaraco.classes
    - importlib_resources  # [py<39]

test:
  requires:
    - pip
    - pytest >=6
    - pytest-runner
    - setuptools_scm >=1.15.0
  source_files:
      - tests/*
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  commands:
    - pip check
    # skip tests on OS-X, the default keychain is not available in the build environment
    - py.test -v tests  # [not osx]
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Store and access your passwords safely
  description: |
    The python keyring lib provides a easy way to access the system keyring
    service from python.  it can be used in any application that needs safe
    password storage.
  doc_url: https://pypi.org/project/keyring/
  dev_url: https://github.com/jaraco/keyring

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - ccordoba12
