travis:
  secure:
    BINSTAR_TOKEN: IibiXVmYJM4DUtb/fp6gBbVVEn4+CCsFkSp5sbFEMzKM098zUIj3oyuo3SGQaMNftyCL19ruyOnN8Z4tN0MdC51n/Jn1NQD1dNw+Ca+CJ7zowUreigMD6bbtHXRBJuZ6qTZ/SHgFVmmpJBS0DnHG0C87fYGbB5fy4X0G62R3T7jwi4Tqejjp+3zArIVDJlXEGZ19YnRIXYc1fY7YmL7/5x8X6ODgogZNxa8KrAzKK7VerjsksQTH7ldSwLUBUBvjnQPgDnjyRmmPm7TtmTfbwWOwGDkxHeSzR/illRMQ9xrN777lMV0Ns7k8vQsa+2i2MwRh1qk8o5nvhHUNwPqaJ/lGOD3FwggBehbOTAb9Rr47LK+BbhwdJT6DdtkNW5wfckBXhYGS0r2L1gbc+d04ZJRkmtllfwDefhTVlGegU+g5rHS4L+OAYK44mR1U3SlHF7T3r058l+k6N3tgmKM0oWUjGXfIAyjXHQBr38P8dSfa43yX667L1TqChWTSu3xUJAFCqMNHoszcR68dz5eyd6gtRaKX8oF95Cbu+wORoIHXsB9vKICRtpoL+DNndGRsirZZAPPfEseMkIeZj2dvcXm0i3YvhUHfi8IGj8qHEqfyqYeAZlz/o+nOypzUysMl5qIQWnplQ4eLI+MkPFslifOSD1G3vHzM1i5egsHfRIY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
