travis:
  secure:
    BINSTAR_TOKEN: SJpIZ0BphLqAr/CfY1aLmh+YExE1S1Fxij9V4XWuWdzhDyTuHOFqdK+HJxtoJhX3ihLPBqc1ovnGa4HEN9EUxFxwe8CYYQE6ZxUhiIZv2ikMShcxhk8QaYz14f+v/pz9dHeNKI+vVij5HcoXuPzhpOAlNg4Qtgpl/fLwPV9WARsIDTyTh61vUHjm1GdBTeXXNVDTXXoN4rbd248U0dtI8F9mzUDLUVv6WnfDO6DAYfH2gxrf4IJmTOiwi/JmiKrky/FNwl7qHz4B86H4m9+cQabUINWg9463BqlRlVGV0v33nJVKzNgSQ7EkTJnuNCcPkXHU3CHsf/GXrUCgio+jw/GDXUwMS1sUBg5j8aehR7Gz+Slg6bZUCv4OJHj4k6R16Mi+k3F/SBMZEz/zNIl3NI9bEyhlEw80aB1nbdj2luE6FZWu43X3FCf4CjBHjFAg+P3vfQLCzKPBuGdgYqrzbRFSTWcw2TLM/U9xxchJRFvyJGWaV1IJfLX+2t/HztZqylzr8yCDwLf/Ty6Z6iUjGtaZhvEBbGtEZJC7evPMMSItIRkxw9vEFx2yfEhUJ2gT0suKn3H8n4EhzUn2hy0eNkYRVENSTp4JvjHMuM2fGuhpSoE6lJPwfSBvgxvdIlC+Z+kI2ZA/KpONxFWqkNcSf94s+kBhx+2V1fKOZdMqUIs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
